config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'

  get 'categories/new'

  root "home#index"

  resources :categories
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  
  default_scope { order(created_at: :desc) }
end

app/models/concerns/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  rescue_from ActiveRecord::RecordNotFound, with: :resource_not_found 
  
  protected
  
    def resource_not_found 
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
  
  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(params_category)
    if @category.save
      flash[:success] = "Categoria cadastrada com sucesso"
      redirect_to categories_path
    else
      flash.now[:danger] = "Categoria nao pode ser cadastrada"
      render :new
    end
  end

  protected  
    def resource_not_found
      message = "A categoria não foi encontrada" 
      flash[:alert] = message
      render "pages/404", status: 404
    end

  private

    def params_category
      params.require(:category).permit(:name, :opening_balance)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/categories/edit.html.erb
<h1>Edit category</h1>

<div class="row">
  <div class="col-md-12">
    
    <% @category.errors.full_messages.each do |message| %>
      <div class="alert alert-danger" role="alert"><%= message %></div>
    <% end %>


    <%= form_for @category, class: "form-horizontal" do |f| %>
      <%= f.label :name, "Nome" %>
      <%= f.text_field :name %> <br>

      <%= f.label :opening_balance, "Saldo inicial" %>
      <%= f.text_field :opening_balance, step: 2 %>

      <%= f.submit "Criar categoria" %>
    <% end %>
  </div>
</div>

app/views/categories/index.html.erb
<h1>Lista de categorias</h1>

<% if @categories.empty? %>
  <h2 id="no-categories">Não há categorias criadas</h2>
<% else %>
  <table class="table">
    <tr>
      <th>name</th>
    </tr>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.name, category_path(category) %></td>
      </tr>
    <% end %>
  </table>  
<% end %>

app/views/categories/new.html.erb
<h1>New category</h1>

<div class="row">
  <div class="col-md-12">
    
    <% @category.errors.full_messages.each do |message| %>
      <div class="alert alert-danger" role="alert"><%= message %></div>
    <% end %>


    <%= form_for @category, class: "form-horizontal" do |f| %>
      <%= f.label :name, "Nome" %>
      <%= f.text_field :name %> <br>

      <%= f.label :opening_balance, "Saldo inicial" %>
      <%= f.text_field :opening_balance, step: 2 %>

      <%= f.submit "Criar categoria" %>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<h1>Showing category</h1>

<p>Nome: <%= @category.name %></p>
<p>Saldo inicial: <%= @category.opening_balance %></p>
<p>Saldo atual: <%= @category.current_balance %></p>

app/views/home/index.html.erb
<%= link_to "Nova Categoria", new_category_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppFinance</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header role="banner">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "App-finance", root_path, class: "navbar-brand" %>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li> <%= link_to "Categorias", categories_path %> </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="#">Link</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="#">Separated link</a></li>
                </ul>
              </li>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
    </header>
    <div class="container">
      <% flash.each do |key, message| %>
        <div class="alert alert-<%= key == 'success' ? 'success' : 'danger' %>" role="alert"><%= message %></div>
      <% end %>

      <%= yield %>
    
    </div>
  </body>
</html>